name: Bug report
description: File a bug report with reproduction details
labels: [bug]
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Clear, concise description of the bug.
    validations:
      required: true
  - type: textarea
    id: repro
    attributes:
      label: Steps to reproduce
      description: Provide a minimal, reproducible example.
      placeholder: |
        1. Command run
        2. Input data/sample
        3. Observed output / error
        4. Expected behavior
    validations:
      required: true
  - type: input
    id: env
    attributes:
      label: Environment
      placeholder: OS, Python, CUDA, package versions
  - type: textarea
    id: logs
    attributes:
      label: Logs/traceback
      render: shell
