blank_issues_enabled: false
contact_links:
  - name: Project README
    url: https://github.com/NVIDIA-Digital-Bio/CodonFM/blob/main/README.md
    about: Start here for setup, quickstart, and usage details
