name: Auto-close PRs
on:
  pull_request:
    types: [opened, reopened, synchronize]
jobs:
  close:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: Close PR with notice
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh pr close ${{ github.event.pull_request.number }} --comment "Thanks for your interest. This repository is read-only and does not accept Pull Requests. Please open an Issue for reproducible bugs."